---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
  namespace: default
  labels:
    app: busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox-container
        image: busybox:latest
        # Keep the container running
        command: [ "/bin/sh", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        resources:
          requests:
            cpu: 30m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi

# verify with:
# kubectl get deployments -n default
# kubectl get pods -n defaultm -or- deployment # when -n is not specified, it defaults to 'default' namespace
# kubectl get pods -n default -o wide # to see node assignment and pod IP
# kubectl describe deployment busybox -n default # describe deployment
# kubectl describe pod <pod-name> -n default # describe pod
# kubectl logs <pod-name> -n default # check logs
# kubectl describe deployment

# Execute commands inside the BusyBox pod
# alias k=kubectl
# k exec -it busybox-8578bccf7-75svv -- /bin/sh # exec into the pod think of it as ssh
# k exec -it busybox-8578bccf7-75svv -- /bin/sh -c "echo Hello from the BusyBox pod" # exec into the pod and run a command
# k exec -it busybox-8578bccf7-75svv -- /bin/sh -c "ls -la /"